Update qlty_coverage.yml

diff --git a/.github/workflows/qlty_coverage.yml b/.github/workflows/qlty_coverage.yml
--- a/.github/workflows/qlty_coverage.yml
+++ b/.github/workflows/qlty_coverage.yml
@@ -38,12 +38,13 @@ jobs:
         # yamllint disable rule:line-length
         run: |
           curl https://qlty.sh | sh || echo "Failed to download Qlty CLI tarball"
-      - name: "iNIT Qlty CLI"
-        run:
+          tar -tvf qlty.tar.xz || echo "Failed to list tarball contents"
+          tar -xpJf qlty.tar.xz --strip-components=1 -C . || echo "Failed to extract Qlty CLI"
+          ls -l || echo "Failed to list extracted files"
+          chmod +x qlty || echo "Failed to make qlty executable"
+          mv qlty /usr/local/bin/ || echo "Failed to move qlty to /usr/local/bin"
           qlty init
-      - name: "Check Qlty CLI Version"
-        run:
-          qlty version
+          qlty version || echo "Qlty CLI not installed correctly"
       - name: "Run Tests and Generate Coverage"
         # yamllint disable rule:line-length
         run: |
